### ISSUE TITLE
Ring Buffer Test Contradicts Instructions

### ISSUE THREAD

**Issue by morsedan** [LambdaSchool/Sprint-Challenge--Data-Structures-Python#224]
The instructions say that a ring buffer is a non-growable data structure. However, the test for the ring buffer implemented with a doubly linked list explicitly tests that it does grow. I think a more elegant implementation than growing the linked list  is to create a linked list of the correct size at initialization. This uses less code and more closely follows the instructions as well as the intent of a circular or ring buffer.

**Comment by seanchen1991** [comment]
Thanks for pointing this out. The exercise has been changed accordingly.

**Comment by morsedan** [comment]
Looks great! Thanks, Sean!
